"use client";
import "./globals.css";
import { ThemeProvider } from "@material-tailwind/react";
import Navbar from "@/Components/Navbar"
import Footer from "@/Components/Footer";

const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <ThemeProvider>
                    <Navbar />
                    {children}
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
